# Generated by Django 5.2.5 on 2025-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_newsarticle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='trading_new_symbol_5ac736_idx',
            old_name='trading_new_symbol_fe7b85_idx',
        ),
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='trading_new_publish_ea23ba_idx',
            old_name='trading_new_publish_27f9a8_idx',
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['symbol'], name='trading_new_symbol_cf7baa_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source'], name='trading_new_source_2a8af0_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['symbol', 'published_at'], name='trading_new_symbol_c6eefd_idx'),
        ),
    ]
