# Generated by Django 5.2.5 on 2025-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_rename_trading_new_symbol_fe7b85_idx_trading_new_symbol_5ac736_idx_and_more'),
    ]

    operations = [
        # User model indexes
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='trading_user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='trading_user_username_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='trading_user_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='trading_user_is_verified_idx'),
        ),
        
        # Stock model indexes
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='trading_stock_exchange_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='trading_stock_sector_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_active'], name='trading_stock_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price'], name='trading_stock_current_price_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['market_cap'], name='trading_stock_market_cap_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_price_update'], name='trading_stock_last_price_update_idx'),
        ),
        
        # MarketData model indexes
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['date'], name='trading_marketdata_date_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['stock', 'date', 'time_period'], name='trading_marketdata_stock_date_period_idx'),
        ),
        
        # Portfolio model indexes
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='trading_portfolio_user_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'is_default'], name='trading_portfolio_user_default_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_active'], name='trading_portfolio_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['total_value'], name='trading_portfolio_total_value_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['created_at'], name='trading_portfolio_created_at_idx'),
        ),
        
        # Holding model indexes
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio'], name='trading_holding_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['stock'], name='trading_holding_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio', 'stock'], name='trading_holding_portfolio_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['current_value'], name='trading_holding_current_value_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['unrealized_gain_loss'], name='trading_holding_gain_loss_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['last_transaction_date'], name='trading_holding_last_transaction_idx'),
        ),
        
        # Transaction model indexes
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio'], name='trading_transaction_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stock'], name='trading_transaction_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'stock'], name='trading_transaction_portfolio_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='trading_transaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='trading_transaction_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='trading_transaction_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'transaction_date'], name='trading_transaction_portfolio_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stock', 'transaction_date'], name='trading_transaction_stock_date_idx'),
        ),
    ]
