# Generated by Django 5.2.5 on 2025-09-07 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_add_all_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('prediction_data', models.JSONField()),
                ('cache_key', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trading_prediction_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM Neural Network'), ('linear', 'Linear Regression'), ('random_forest', 'Random Forest')], default='lstm', max_length=20)),
                ('status', models.CharField(choices=[('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed'), ('outdated', 'Outdated')], default='training', max_length=20)),
                ('sequence_length', models.IntegerField(default=60)),
                ('training_data_points', models.IntegerField()),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('train_rmse', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('val_rmse', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('train_mae', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('val_mae', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('model_file_path', models.CharField(max_length=500)),
                ('scaler_file_path', models.CharField(max_length=500)),
                ('metadata_file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_prediction_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trading_prediction_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('next_day', 'Next Day'), ('next_week', 'Next Week'), ('next_month', 'Next Month')], default='next_day', max_length=20)),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price_change', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price_change_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('confidence_level', models.CharField(choices=[('low', 'Low (< 0.3)'), ('medium', 'Medium (0.3 - 0.7)'), ('high', 'High (> 0.7)')], max_length=10)),
                ('prediction_date', models.DateField()),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('actual_price_change', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('actual_price_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('prediction_accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('input_features', models.JSONField(blank=True, default=dict)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'trading_price_predictions',
                'ordering': ['-prediction_timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_portfol_a57cde_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_stock_i_4a555e_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_portfol_c03506_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_current_d42515_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_unreali_4dc855_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_hol_last_tr_732dc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_portfolio_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_portfolio_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_current_value_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_gain_loss_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='trading_holding_last_transaction_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_mar_stock_i_642423_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_mar_stock_i_0c1436_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_mar_date_c3afe1_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_mar_stock_i_1c596b_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_marketdata_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='trading_marketdata_stock_date_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='trading_new_symbol_5ac736_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='trading_new_publish_ea23ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='trading_new_symbol_cf7baa_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='trading_new_source_2a8af0_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='trading_new_symbol_c6eefd_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_por_user_id_3d489e_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_por_user_id_d18b69_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_por_is_acti_0fe898_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_por_total_v_5489a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_por_created_e103a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_portfolio_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_portfolio_user_default_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_portfolio_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_portfolio_total_value_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='trading_portfolio_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_symbol_428c14_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_exchang_42f3ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_sector_a252f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_is_acti_8e4c0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_current_57d1fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_market__f1ee03_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_sto_last_pr_a9cf71_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_exchange_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_sector_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_current_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_market_cap_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='trading_stock_last_price_update_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_portfol_cfddb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_stock_i_174ac5_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_portfol_8bfad7_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_transac_d8da71_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_status_f3cf9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_transac_0766ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_portfol_afefdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_tra_stock_i_11e5c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_portfolio_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_portfolio_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_portfolio_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trading_transaction_stock_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_use_email_929c79_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_use_usernam_ef7e90_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_use_created_812dc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_use_is_veri_5de77a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_user_username_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_user_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='trading_user_is_verified_idx',
        ),
        migrations.AddIndex(
            model_name='predictioncache',
            index=models.Index(fields=['stock_symbol', 'expires_at'], name='trading_pre_stock_s_f42f61_idx'),
        ),
        migrations.AddIndex(
            model_name='predictioncache',
            index=models.Index(fields=['cache_key'], name='trading_pre_cache_k_2c1c13_idx'),
        ),
        migrations.AddField(
            model_name='predictionmodel',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_models', to='trading.stock'),
        ),
        migrations.AddField(
            model_name='priceprediction',
            name='prediction_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='trading.predictionmodel'),
        ),
        migrations.AddField(
            model_name='priceprediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='trading.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='predictionmodel',
            unique_together={('stock', 'model_type')},
        ),
        migrations.AddIndex(
            model_name='priceprediction',
            index=models.Index(fields=['stock', 'prediction_date'], name='trading_pri_stock_i_3fe2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='priceprediction',
            index=models.Index(fields=['prediction_timestamp'], name='trading_pri_predict_b03447_idx'),
        ),
        migrations.AddIndex(
            model_name='priceprediction',
            index=models.Index(fields=['confidence_level'], name='trading_pri_confide_5df17d_idx'),
        ),
    ]
